### ISSUE TITLE
add ambient occlusion (ray-tracing) benchmarks

### ISSUE THREAD

**Issue by anp** [anp/lolbench#39] opened 2018-10-04 20:36 UTC
https://github.com/gnzlbg/aobench

The readme shows how to run the scalar, vectorized, and parallel versions. Probably it only makes sense to add the `scalar` and `scalar_par` benchmarks initially. The `vector` and `vector_par` benchmarks use `std::simd` and that's still in flux.

_Originally posted by @gnzlbg in https://github.com/anp/lolbench/issues/1#issuecomment-394876648_

**Comment by anp** [comment] 2018-10-04 20:37
IIRC std::simd has been settling down some, but not sure whether its stable enough for us to care about including in a benchmark yet.

**Comment by gnzlbg** [comment] 2018-10-05 08:35
Duplicate of #42 (ISPC has a benchmark for this, which has already been ported)

**Closed** 2018-10-05 16:16 UTC
Labels: benchmark needed
